spring.application.name=rare-x-back


spring.profiles.active=local

# MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-validity=${JWT_ACCESS_TOKEN_VALIDITY}
jwt.refresh-token-validity=${JWT_REFRESH_TOKEN_VALIDITY}