spring.application.name=rare-x-back


spring.profiles.active=local

# MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Display the actual values bound to SQL query parameters (?) in the logs
logging.level.org.hibernate.orm.jdbc.bind=trace

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-validity=${JWT_ACCESS_TOKEN_VALIDITY}
jwt.refresh-token-validity=${JWT_REFRESH_TOKEN_VALIDITY}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}

# Toss Payment
toss.client-key=${TOSS_CLIENT_KEY}
toss.secret-key=${TOSS_SECRET_KEY}
toss.api-version=2022-11-16
toss.api-url=https://api.tosspayments.com/v1/

# Inspection Center
inspection-center.address=123 Teheran-ro, Gangnam-gu, Seoul, Korea
inspection-center.zipcode=06234
